#!/bin/bash
set -euo pipefail

# Refresh the README's apps section on `main` after a build.
#
# The section (between <!-- APPS_START --> and <!-- APPS_END -->) is generated by obtainium.py
# from the app config (configs/patches/*.toml) and the versions and applied patches of what was
# last published (state/archive/*.json); both are read from the tip of main. Nothing
# else in README.md is touched, and nothing is written when the result is unchanged.
#
# Plumbing only, like commit_to_main.sh: the new README is built from origin/main's own copy
# and committed onto origin/main's tip with a temporary index, so the build's working tree is
# never switched or dirtied, and a human push to main in the meantime is built upon, not
# overwritten (the generation reruns against the new tip on every retry).
#
# Presentation, not data: the workflow step runs it with continue-on-error, so a failure here
# can never cost a build its release.
#
# Env: GITHUB_REPOSITORY (owner/repo, required), BUILD_TAG (for the commit message, optional)

REPO="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY not set}"
TAG="${BUILD_TAG:-}"
SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-github-actions[bot]}"
export GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-41898282+github-actions[bot]@users.noreply.github.com}"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# build_commit: regenerate against origin/main's tip and echo the new commit.
# Returns 0 with a commit, 3 when the section is already current, 2 on any failure. The two
# are kept apart on purpose: this runs under `if`/`$( )`, where `set -e` does not apply, so every
# step that can fail says so explicitly - a broken generation must never read as "nothing to do".
build_commit() {
	local base=$1 idx blob tree manifests=() ch
	mkdir -p "$WORK/cfg" || return 2
	git archive "$base" configs/patches | tar -x -C "$WORK/cfg" || return 2
	git show "$base:README.md" > "$WORK/README.md" || return 2
	for ch in stable beta; do
		# a channel that has never published has no archive manifest yet; that is not an error
		if git cat-file -e "$base:state/archive/$ch.json" 2> /dev/null; then
			git show "$base:state/archive/$ch.json" > "$WORK/$ch.json" || return 2
			manifests+=(--manifest "$WORK/$ch.json")
		fi
	done
	python3 "$SCRIPTS/obtainium.py" --configs "$WORK/cfg/configs/patches" --repo "$REPO" --readme "$WORK/README.md" "${manifests[@]}" > /dev/null || return 2
	if git show "$base:README.md" | cmp -s - "$WORK/README.md"; then
		return 3
	fi
	idx=$(mktemp) || return 2
	rm -f "$idx"
	GIT_INDEX_FILE=$idx git read-tree "$base" || return 2
	blob=$(git hash-object -w "$WORK/README.md") || return 2
	GIT_INDEX_FILE=$idx git update-index --cacheinfo "100644,$blob,README.md" || return 2
	tree=$(GIT_INDEX_FILE=$idx git write-tree) || return 2
	rm -f "$idx"
	git commit-tree "$tree" -p "$base" -m "docs: refresh the app table${TAG:+ after build $TAG} [skip ci]" || return 2
}

for attempt in 1 2 3; do
	git fetch -q origin main
	base=$(git rev-parse origin/main)
	rc=0
	new=$(build_commit "$base") || rc=$?
	case "$rc" in
		0) ;;
		3)
			echo "README app table is already up to date."
			exit 0
			;;
		*)
			echo "FATAL: could not generate the README app table (see the error above)." >&2
			exit 1
			;;
	esac
	if git push -q origin "$new:refs/heads/main" 2> /dev/null; then
		echo "Refreshed the README app table ($new)."
		exit 0
	fi
	echo "Push attempt $attempt failed (main moved?); regenerating on the new tip..."
	sleep 3
done
echo "FATAL: could not push the README refresh to main after 3 attempts." >&2
exit 1
