name: Manual CI

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: "Select the config file to use"
        required: true
        type: choice
        default: ".github/configs/config.manual.toml"
        options:
          - ".github/configs/config.manual.toml"
          - ".github/configs/config.dev.updated.json"
          - ".github/configs/config.stable.updated.json"

concurrency:
  group: ci
  cancel-in-progress: false

# Added permissions block to resolve the contents: write error
permissions:
  contents: write

jobs:
  build_manual:
    uses: ./.github/workflows/build.yml
    with:
      config_file: ${{ inputs.config_file }}
    secrets: inherit

  trigger_cleanup:
    needs: [build_manual]
    if: ${{ always() && needs.build_manual.result == 'success' }}
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit

  trigger_website_update:
    needs: [build_manual, trigger_cleanup]
    if: ${{ always() && needs.build_manual.result == 'success' }}
    uses: ./.github/workflows/update-website.yml
    secrets: inherit

  trigger_notify_failure:
    needs: [build_manual]
    if: ${{ failure() }}
    uses: ./.github/workflows/notify.yml
    with:
      workflow_name: "Manual CI"
    secrets: inherit
