name: Notify

on:
  issues:
    types: [ opened, closed, reopened ]
  pull_request:
    types: [ opened, closed, reopened ]
  workflow_call:
    inputs:
      workflow_name:
        required: false
        type: string

concurrency:
  group: notify
  cancel-in-progress: false

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Send Notification to Telegram
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: "${{ vars.TG_CHAT_ID }}"
          TG_THREAD_ID: "${{ vars.TG_THREAD_NOTIFY }}"
          EVENT_NAME: ${{ github.event_name }}
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}
          ACTION: ${{ github.event.action }}
          WF_NAME: ${{ inputs.workflow_name }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          REF_NAME: ${{ github.ref_name }}
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_COMMITS: ${{ github.event.pull_request.commits }}
          PR_FILES: ${{ github.event.pull_request.changed_files }}
          PR_ADD: ${{ github.event.pull_request.additions }}
          PR_DEL: ${{ github.event.pull_request.deletions }}
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          ISSUE_NUM: ${{ github.event.issue.number }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: bash .github/scripts/notify_send_telegram.sh
